# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib

QT += core sql
CONFIG += staticlib
DEFINES += QT_DLL DBMANAGER_LIB QT_SQL_LIB
INCLUDEPATH += .

DESTDIR = $$PWD/bin

CONFIG(debug,debug|release) {
    TARGET = DBManager_d
}

CONFIG(release,debug|release) {
    TARGET = DBManager
}

include(DBManager.pri)
