# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = test
QT += core sql
CONFIG += qtestlib console
DEFINES += QT_DLL QT_TESTLIB_LIB QT_SQL_LIB
INCLUDEPATH += $$PWD/../DBManager

DEPENDPATH += .

CONFIG(debug,debug|release) {
    LIBS += -L"$$PWD/../DBManager/bin" \
        -lDBManager_d
}

CONFIG(release,debug|release) {
    LIBS += -L"$$PWD/../DBManager/bin" \
        -lDBManager
}


include(test.pri)
